---
name: orinoco-dev
include:
- path: "./compose/orinoco-db.yml"
  project_directory: "./"
  env_file: "./development.env"
- path: "./compose/railsapp.yml"
  project_directory: "./"
  env_file: "./development.env"
- path: "./compose/goaws.yml"
  project_directory: "./"
  env_file: "./development.env"
- path: "./compose/redis.yml"
  project_directory: "./"
  env_file: "./development.env"
